###################################################
# header_music.py
# This file contains declarations for music tracks
# DO NOT EDIT THIS FILE!
###################################################


mtf_culture_1                          = 0x00000001 #1
mtf_culture_2                          = 0x00000002 #2
mtf_culture_3                          = 0x00000004 #4
mtf_culture_4                          = 0x00000008 #8
mtf_culture_5                          = 0x00000010 #16
mtf_culture_6                          = 0x00000020 #32
mtf_culture_all                        = 0x0000003F #63


############1257 AD special cases
mtf_culture_AD6 = 6
#mtf_culture_AD_dunno = 8388608
mtf_culture_AD_dunno2 = 32
mtf_culture_AD_nil = 0

##mtf_sit_map_travel                 = 0x00000001
##mtf_sit_attack                     = 0x00000002
##mtf_sit_defense                    = 0x00000004
##mtf_sit_raid_attack                = 0x00000010
##mtf_sit_raid_defense               = 0x00000020
##
mtf_looping                            = 0x00000040 #64
mtf_start_immediately                  = 0x00000080 #128
mtf_persist_until_finished             = 0x00000100 #256

mtf_sit_tavern                         = 0x00000200 #512
mtf_sit_fight                          = 0x00000400 #1024
mtf_sit_multiplayer_fight              = 0x00000800 #2048
mtf_sit_ambushed                       = 0x00001000 #4096
mtf_sit_town                           = 0x00002000 #8192
mtf_sit_town_infiltrate                = 0x00004000 #16384
mtf_sit_killed                         = 0x00008000 #32768
mtf_sit_travel                         = 0x00010000 #65536
mtf_sit_arena                          = 0x00020000 #131072
mtf_sit_siege                          = 0x00040000 #262144
mtf_sit_night                          = 0x00080000 #524288
mtf_sit_day                            = 0x00100000 #1048576
mtf_sit_encounter_hostile              = 0x00200000 #2097152
mtf_sit_main_title                     = 0x00400000 #4194304
mtf_sit_victorious                     = 0x00800000 #8388608
mtf_sit_feast                          = 0x01000000 #1677216
mtf_module_track                       = 0x10000000 ##set this flag for tracks placed under module folder


